 
export default async () => {
    const t = {
        ["./modules/image/enums"]: await import("./modules/image/enums"),
        ["./lib/enums/database"]: await import("./lib/enums/database"),
        ["./modules/image/responses/model/image.model"]: await import("./modules/image/responses/model/image.model"),
        ["./modules/image/responses/list-images.response"]: await import("./modules/image/responses/list-images.response")
    };
    return { "@nestjs/swagger": { "models": [[import("./modules/image/dto/upload-image.dto"), { "UploadImageDto": { title: { required: true, type: () => String, minLength: 1, maxLength: 255 }, width: { required: false, type: () => Number, minimum: 1, maximum: 8192 }, height: { required: false, type: () => Number, minimum: 1, maximum: 8192 } } }], [import("./modules/image/dto/list-images.dto"), { "ListImagesDto": { search: { required: false, type: () => String, minLength: 1, maxLength: 100 }, limit: { required: true, type: () => Number, default: 25, maximum: 500, minimum: 1 }, offset: { required: true, type: () => Number, default: 0, minimum: 0 }, orderBy: { required: true, enum: t["./modules/image/enums"].ImageOrderBy, minLength: 1, maxLength: 255 }, orderWay: { required: true, enum: t["./lib/enums/database"].OrderWay } } }], [import("./modules/image/dto/image.dto"), { "ImageDto": { imageUUID: { required: true, type: () => String, format: "uuid" } } }], [import("./modules/image/responses/model/image.model"), { "ImageModel": { imageUUID: { required: true, type: () => String }, title: { required: true, type: () => String }, url: { required: true, type: () => String }, width: { required: true, type: () => Number }, height: { required: true, type: () => Number }, mimeType: { required: true, type: () => String }, size: { required: true, type: () => Number } } }], [import("./modules/image/responses/list-images.response"), { "ListImagesResponse": { images: { required: true, type: () => [t["./modules/image/responses/model/image.model"].ImageModel] }, count: { required: true, type: () => Number } } }]], "controllers": [[import("./modules/health-check/health-check.controller"), { "HealthCheckController": { "healthCheck": { type: Object } } }], [import("./modules/image/image.controller"), { "ImageController": { "uploadImage": {}, "listImages": { type: t["./modules/image/responses/list-images.response"].ListImagesResponse }, "getImageById": { type: t["./modules/image/responses/model/image.model"].ImageModel } } }]] } };
};